Загрузим данные "Титаник"

In [18]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

In [19]:
preprocessor = DataPreprocessor(df)

Исходные данные

In [20]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Пропуски по столбцам

In [21]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Удалим и заполним столбцы

In [22]:
remove_df = preprocessor.remove_missing(threshold=0.5, fill_strategy='median')

In [23]:
remove_df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

Закодируем категориальные данные

In [24]:
encode_df = preprocessor.encode_categorical()

In [25]:
encode_df

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,"Name_Abbing, Mr. Anthony","Name_Abbott, Mr. Rossmore Edward","Name_Abbott, Mrs. Stanton (Rosa Hunt)",...,Ticket_W./C. 14263,Ticket_W./C. 6607,Ticket_W./C. 6608,Ticket_W./C. 6609,Ticket_W.E.P. 5734,Ticket_W/C 14208,Ticket_WE/P 5735,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,22.0,1,0,7.2500,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,2,1,1,38.0,1,0,71.2833,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,1,3,26.0,0,0,7.9250,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,4,1,1,35.0,1,0,53.1000,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,5,0,3,35.0,0,0,8.0500,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,27.0,0,0,13.0000,0,0,0,...,0,0,0,0,0,0,0,0,0,1
887,888,1,1,19.0,0,0,30.0000,0,0,0,...,0,0,0,0,0,0,0,0,0,1
888,889,0,3,28.0,1,2,23.4500,0,0,0,...,0,1,0,0,0,0,0,0,0,1
889,890,1,1,26.0,0,0,30.0000,0,0,0,...,0,0,0,0,0,0,0,1,0,0
890,891,0,3,32.0,0,0,7.7500,0,0,0,...,0,0,0,0,0,0,0,0,1,0

Нормализуем численные признаки

In [26]:
normalize_df = preprocessor.normalize_numeric()

In [27]:
normalize_df['Age']

0      0.271174
1      0.472229
2      0.321438
3      0.434531
4      0.434531
         ...
886    0.334004
887    0.233476
888    0.346569
889    0.321438
890    0.396833
Name: Age, Length: 891, dtype: float64

Выпоолним все операции и посмотрим на результат

In [28]:
full_process_df = preprocessor.fit_transform()

In [29]:
full_process_df

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,"Name_Abbing, Mr. Anthony","Name_Abbott, Mr. Rossmore Edward","Name_Abbott, Mrs. Stanton (Rosa Hunt)",...,Ticket_W./C. 14263,Ticket_W./C. 6607,Ticket_W./C. 6608,Ticket_W./C. 6609,Ticket_W.E.P. 5734,Ticket_W/C 14208,Ticket_WE/P 5735,Embarked_C,Embarked_Q,Embarked_S
0,0.000000,0.0,1.0,0.271174,0.125,0.000000,0.014151,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.001124,1.0,0.0,0.472229,0.125,0.000000,0.139136,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.002247,1.0,1.0,0.321438,0.000,0.000000,0.015469,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.003371,1.0,0.0,0.434531,0.125,0.000000,0.103644,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.004494,0.0,1.0,0.434531,0.000,0.000000,0.015713,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0.995506,0.0,0.5,0.334004,0.000,0.000000,0.025374,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
887,0.996629,1.0,0.0,0.233476,0.000,0.000000,0.058556,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
888,0.997753,0.0,1.0,0.346569,0.125,0.333333,0.045771,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
889,0.998876,1.0,0.0,0.321438,0.000,0.000000,0.058556,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
890,1.000000,0.0,1.0,0.396833,0.000,0.000000,0.015127,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [30]:
preprocessor.get_info()

{'removed_columns': ['Cabin'],
 'fill_values': {'Age': {'value': 28.0, 'strategy': 'median'},
  'Embarked': {'value': 'S', 'strategy': 'median'}},
 'one_hot_columns': ['Name_Abbing, Mr. Anthony',
  'Name_Abbott, Mr. Rossmore Edward',
  'Name_Abbott, Mrs. Stanton (Rosa Hunt)',
  'Name_Abelson, Mr. Samuel',
  'Name_Abelson, Mrs. Samuel (Hannah Wizosky)',
  'Name_Adahl, Mr. Mauritz Nils Martin',
  'Name_Adams, Mr. John',
  'Name_Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
  'Name_Aks, Mrs. Sam (Leah Rosen)',
  'Name_Albimona, Mr. Nassef Cassem',
  'Name_Alexander, Mr. William',
  'Name_Alhomaki, Mr. Ilmari Rudolf',
  'Name_Ali, Mr. Ahmed',
  'Name_Ali, Mr. William',
  'Name_Allen, Miss. Elisabeth Walton',
  'Name_Allen, Mr. William Henry',
  'Name_Allison, Master. Hudson Trevor',
  'Name_Allison, Miss. Helen Loraine',
  'Name_Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
  'Name_Allum, Mr. Owen George',
  'Name_Andersen-Jensen, Miss. Carla Christine Nielsine',
  'Name_Anderson, Mr. Harry',
  'Name_Andersson, Master. Sigvard Harald Elias',
  'Name_Andersson, Miss. Ebba Iris Alfrida',
  'Name_Andersson, Miss. Ellis Anna Maria',
  'Name_Andersson, Miss. Erna Alexandra',
  'Name_Andersson, Miss. Ingeborg Constanzia',
  'Name_Andersson, Miss. Sigrid Elisabeth',
  'Name_Andersson, Mr. Anders Johan',
  'Name_Andersson, Mr. August Edvard ("Wennerstrom")',
  'Name_Andersson, Mrs. Anders Johan (Alfrida Konstantia Brogren)',
  'Name_Andreasson, Mr. Paul Edvin',
  'Name_Andrew, Mr. Edgardo Samuel',
  'Name_Andrews, Miss. Kornelia Theodosia',
  'Name_Andrews, Mr. Thomas Jr',
  'Name_Angle, Mrs. William A (Florence "Mary" Agnes Hughes)',
  'Name_Appleton, Mrs. Edward Dale (Charlotte Lamson)',
  'Name_Arnold-Franchi, Mr. Josef',
  'Name_Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
  'Name_Artagaveytia, Mr. Ramon',
  'Name_Asim, Mr. Adola',
  'Name_Asplund, Master. Clarence Gustaf Hugo',
  'Name_Asplund, Master. Edvin Rojj Felix',
  'Name_Asplund, Miss. Lillian Gertrud',
  'Name_Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
  'Name_Astor, Mrs. John Jacob (Madeleine Talmadge Force)',
  'Name_Attalah, Miss. Malake',
  'Name_Attalah, Mr. Sleiman',
  'Name_Aubart, Mme. Leontine Pauline',
  'Name_Augustsson, Mr. Albert',
  'Name_Ayoub, Miss. Banoura',
  'Name_Backstrom, Mr. Karl Alfred',
  'Name_Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
  'Name_Baclini, Miss. Eugenie',
  'Name_Baclini, Miss. Helene Barbara',
  'Name_Baclini, Miss. Marie Catherine',
  'Name_Baclini, Mrs. Solomon (Latifa Qurban)',
  'Name_Badt, Mr. Mohamed',
  'Name_Bailey, Mr. Percy Andrew',
  'Name_Balkic, Mr. Cerin',
  'Name_Ball, Mrs. (Ada E Hall)',
  'Name_Banfield, Mr. Frederick James',
  'Name_Barah, Mr. Hanna Assi',
  'Name_Barbara, Miss. Saiide',
  'Name_Barbara, Mrs. (Catherine David)',
  'Name_Barber, Miss. Ellen "Nellie"',
  'Name_Barkworth, Mr. Algernon Henry Wilson',
  'Name_Barton, Mr. David John',
  'Name_Bateman, Rev. Robert James',
  'Name_Baumann, Mr. John D',
  'Name_Baxter, Mr. Quigg Edmond',
  'Name_Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
  'Name_Bazzani, Miss. Albina',
  'Name_Beane, Mr. Edward',
  'Name_Beane, Mrs. Edward (Ethel Clarke)',
  'Name_Beavan, Mr. William Thomas',
  'Name_Becker, Master. Richard F',
  'Name_Becker, Miss. Marion Louise',
  'Name_Beckwith, Mr. Richard Leonard',
  'Name_Beckwith, Mrs. Richard Leonard (Sallie Monypeny)',
  'Name_Beesley, Mr. Lawrence',
  'Name_Behr, Mr. Karl Howell',
  'Name_Bengtsson, Mr. John Viktor',
  'Name_Berglund, Mr. Karl Ivar Sven',
  'Name_Berriman, Mr. William John',
  'Name_Betros, Mr. Tannous',
  'Name_Bidois, Miss. Rosalie',
  'Name_Bing, Mr. Lee',
  'Name_Birkeland, Mr. Hans Martin Monsen',
  'Name_Bishop, Mr. Dickinson H',
  'Name_Bishop, Mrs. Dickinson H (Helen Walton)',
  'Name_Bissette, Miss. Amelia',
  'Name_Bjornstrom-Steffansson, Mr. Mauritz Hakan',
  'Name_Blackwell, Mr. Stephen Weart',
  'Name_Blank, Mr. Henry',
  'Name_Bonnell, Miss. Elizabeth',
  'Name_Bostandyeff, Mr. Guentcho',
  'Name_Boulos, Miss. Nourelain',
  'Name_Boulos, Mr. Hanna',
  'Name_Boulos, Mrs. Joseph (Sultana)',
  'Name_Bourke, Miss. Mary',
  'Name_Bourke, Mr. John',
  'Name_Bourke, Mrs. John (Catherine)',
  'Name_Bowen, Mr. David John "Dai"',
  'Name_Bowerman, Miss. Elsie Edith',
  'Name_Bracken, Mr. James H',
  'Name_Bradley, Mr. George ("George Arthur Brayton")',
  'Name_Braund, Mr. Lewis Richard',
  'Name_Braund, Mr. Owen Harris',
  'Name_Brewe, Dr. Arthur Jackson',
  'Name_Brocklebank, Mr. William Alfred',
  'Name_Brown, Miss. Amelia "Mildred"',
  'Name_Brown, Mr. Thomas William Solomon',
  'Name_Brown, Mrs. James Joseph (Margaret Tobin)',
  'Name_Brown, Mrs. Thomas William Solomon (Elizabeth Catherine Ford)',
  'Name_Bryhl, Mr. Kurt Arnold Gottfrid',
  'Name_Burke, Mr. Jeremiah',
  'Name_Burns, Miss. Elizabeth Margaret',
  'Name_Buss, Miss. Kate',
  'Name_Butler, Mr. Reginald Fenton',
  'Name_Butt, Major. Archibald Willingham',
  'Name_Byles, Rev. Thomas Roussel Davids',
  'Name_Bystrom, Mrs. (Karolina)',
  'Name_Cacic, Miss. Marija',
  'Name_Cacic, Mr. Luka',
  'Name_Cairns, Mr. Alexander',
  'Name_Calderhead, Mr. Edward Pennington',
  'Name_Caldwell, Master. Alden Gates',
  'Name_Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)',
  'Name_Calic, Mr. Jovo',
  'Name_Calic, Mr. Petar',
  'Name_Cameron, Miss. Clear Annie',
  'Name_Campbell, Mr. William',
  'Name_Canavan, Miss. Mary',
  'Name_Cann, Mr. Ernest Charles',
  'Name_Caram, Mrs. Joseph (Maria Elias)',
  'Name_Carbines, Mr. William',
  'Name_Cardeza, Mr. Thomas Drake Martinez',
  'Name_Carlsson, Mr. August Sigfrid',
  'Name_Carlsson, Mr. Frans Olof',
  'Name_Carr, Miss. Helen "Ellen"',
  'Name_Carrau, Mr. Francisco M',
  'Name_Carter, Master. William Thornton II',
  'Name_Carter, Miss. Lucile Polk',
  'Name_Carter, Mr. William Ernest',
  'Name_Carter, Mrs. Ernest Courtenay (Lilian Hughes)',
  'Name_Carter, Mrs. William Ernest (Lucile Polk)',
  'Name_Carter, Rev. Ernest Courtenay',
  'Name_Cavendish, Mr. Tyrell William',
  'Name_Celotti, Mr. Francesco',
  'Name_Chaffee, Mr. Herbert Fuller',
  'Name_Chambers, Mr. Norman Campbell',
  'Name_Chambers, Mrs. Norman Campbell (Bertha Griggs)',
  'Name_Chapman, Mr. Charles Henry',
  'Name_Chapman, Mr. John Henry',
  'Name_Charters, Mr. David',
  'Name_Cherry, Miss. Gladys',
  'Name_Chibnall, Mrs. (Edith Martha Bowerman)',
  'Name_Chip, Mr. Chang',
  'Name_Christmann, Mr. Emil',
  'Name_Christy, Miss. Julie Rachel',
  'Name_Chronopoulos, Mr. Apostolos',
  'Name_Clarke, Mrs. Charles V (Ada Maria Winfield)',
  'Name_Cleaver, Miss. Alice',
  'Name_Clifford, Mr. George Quincy',
  'Name_Coelho, Mr. Domingos Fernandeo',
  'Name_Cohen, Mr. Gurshon "Gus"',
  'Name_Coleff, Mr. Peju',
  'Name_Coleff, Mr. Satio',
  'Name_Coleridge, Mr. Reginald Charles',
  'Name_Collander, Mr. Erik Gustaf',
  'Name_Colley, Mr. Edward Pomeroy',
  'Name_Collyer, Miss. Marjorie "Lottie"',
  'Name_Collyer, Mr. Harvey',
  'Name_Collyer, Mrs. Harvey (Charlotte Annie Tate)',
  'Name_Compton, Miss. Sara Rebecca',
  'Name_Connaghton, Mr. Michael',
  'Name_Connolly, Miss. Kate',
  'Name_Connors, Mr. Patrick',
  'Name_Cook, Mr. Jacob',
  'Name_Cor, Mr. Liudevit',
  'Name_Corn, Mr. Harry',
  'Name_Coutts, Master. Eden Leslie "Neville"',
  'Name_Coutts, Master. William Loch "William"',
  'Name_Coxon, Mr. Daniel',
  'Name_Crease, Mr. Ernest James',
  'Name_Cribb, Mr. John Hatfield',
  'Name_Crosby, Capt. Edward Gifford',
  'Name_Crosby, Miss. Harriet R',
  'Name_Culumovic, Mr. Jeso',
  'Name_Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'Name_Cunningham, Mr. Alfred Fleming',
  'Name_Dahl, Mr. Karl Edwart',
  'Name_Dahlberg, Miss. Gerda Ulrika',
  'Name_Dakic, Mr. Branko',
  'Name_Daly, Mr. Eugene Patrick',
  'Name_Daly, Mr. Peter Denis ',
  'Name_Danbom, Mr. Ernst Gilbert',
  'Name_Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)',
  'Name_Daniel, Mr. Robert Williams',
  'Name_Danoff, Mr. Yoto',
  'Name_Dantcheff, Mr. Ristiu',
  'Name_Davidson, Mr. Thornton',
  'Name_Davies, Master. John Morgan Jr',
  'Name_Davies, Mr. Alfred J',
  'Name_Davies, Mr. Charles Henry',
  'Name_Davis, Miss. Mary',
  'Name_Davison, Mrs. Thomas Henry (Mary E Finck)',
  'Name_Dean, Master. Bertram Vere',
  'Name_Dean, Mr. Bertram Frank',
  'Name_Denkoff, Mr. Mitto',
  'Name_Dennis, Mr. Samuel',
  'Name_Devaney, Miss. Margaret Delia',
  'Name_Dick, Mr. Albert Adrian',
  'Name_Dick, Mrs. Albert Adrian (Vera Gillespie)',
  'Name_Dimic, Mr. Jovan',
  'Name_Dodge, Master. Washington',
  'Name_Doharr, Mr. Tannous',
  'Name_Doling, Miss. Elsie',
  'Name_Doling, Mrs. John T (Ada Julia Bone)',
  'Name_Dooley, Mr. Patrick',
  'Name_Dorking, Mr. Edward Arthur',
  'Name_Douglas, Mr. Walter Donald',
  'Name_Dowdell, Miss. Elizabeth',
  'Name_Downton, Mr. William James',
  'Name_Drazenoic, Mr. Jozef',
  'Name_Drew, Mrs. James Vivian (Lulu Thorne Christian)',
  'Name_Duane, Mr. Frank',
  'Name_Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
  'Name_Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")',
  'Name_Duran y More, Miss. Asuncion',
  'Name_Edvardsson, Mr. Gustaf Hjalmar',
  'Name_Eitemiller, Mr. George Floyd',
  'Name_Eklund, Mr. Hans Linus',
  'Name_Ekstrom, Mr. Johan',
  'Name_Elias, Mr. Dibo',
  'Name_Elias, Mr. Joseph Jr',
  'Name_Elias, Mr. Tannous',
  'Name_Elsbury, Mr. William James',
  'Name_Emanuel, Miss. Virginia Ethel',
  'Name_Emir, Mr. Farred Chehab',
  'Name_Endres, Miss. Caroline Louise',
  'Name_Eustis, Miss. Elizabeth Mussey',
  'Name_Fahlstrom, Mr. Arne Jonas',
  'Name_Farrell, Mr. James',
  'Name_Farthing, Mr. John',
  'Name_Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
  'Name_Fischer, Mr. Eberhard Thelander',
  'Name_Fleming, Miss. Margaret',
  'Name_Flynn, Mr. James',
  'Name_Flynn, Mr. John',
  'Name_Flynn, Mr. John Irwin ("Irving")',
  'Name_Foo, Mr. Choong',
  'Name_Ford, Miss. Doolina Margaret "Daisy"',
  'Name_Ford, Miss. Robina Maggie "Ruby"',
  'Name_Ford, Mr. William Neal',
  'Name_Ford, Mrs. Edward (Margaret Ann Watson)',
  'Name_Foreman, Mr. Benjamin Laventall',
  'Name_Fortune, Miss. Alice Elizabeth',
  'Name_Fortune, Miss. Mabel Helen',
  'Name_Fortune, Mr. Charles Alexander',
  'Name_Fortune, Mr. Mark',
  'Name_Fox, Mr. Stanley Hubert',
  'Name_Francatelli, Miss. Laura Mabel',
  'Name_Frauenthal, Dr. Henry William',
  'Name_Frauenthal, Mrs. Henry William (Clara Heinsheimer)',
  'Name_Frolicher, Miss. Hedwig Margaritha',
  'Name_Frolicher-Stehli, Mr. Maxmillian',
  'Name_Frost, Mr. Anthony Wood "Archie"',
  'Name_Fry, Mr. Richard',
  'Name_Funk, Miss. Annie Clemmer',
  'Name_Futrelle, Mr. Jacques Heath',
  'Name_Futrelle, Mrs. Jacques Heath (Lily May Peel)',
  'Name_Fynney, Mr. Joseph J',
  'Name_Gale, Mr. Shadrach',
  'Name_Gallagher, Mr. Martin',
  'Name_Garfirth, Mr. John',
  'Name_Garside, Miss. Ethel',
  'Name_Gaskell, Mr. Alfred',
  'Name_Gavey, Mr. Lawrence',
  'Name_Gee, Mr. Arthur H',
  'Name_Gheorgheff, Mr. Stanio',
  'Name_Giglio, Mr. Victor',
  'Name_Giles, Mr. Frederick Edward',
  'Name_Gilinski, Mr. Eliezer',
  'Name_Gill, Mr. John William',
  'Name_Gillespie, Mr. William Henry',
  'Name_Gilnagh, Miss. Katherine "Katie"',
  'Name_Givard, Mr. Hans Kristensen',
  'Name_Glynn, Miss. Mary Agatha',
  'Name_Goldenberg, Mr. Samuel L',
  'Name_Goldenberg, Mrs. Samuel L (Edwiga Grabowska)',
  'Name_Goldschmidt, Mr. George B',
  'Name_Goldsmith, Master. Frank John William "Frankie"',
  'Name_Goldsmith, Mr. Frank John',
  'Name_Goldsmith, Mrs. Frank John (Emily Alice Brown)',
  'Name_Goncalves, Mr. Manuel Estanslas',
  'Name_Goodwin, Master. Harold Victor',
  'Name_Goodwin, Master. Sidney Leonard',
  'Name_Goodwin, Master. William Frederick',
  'Name_Goodwin, Miss. Lillian Amy',
  'Name_Goodwin, Mr. Charles Edward',
  'Name_Goodwin, Mrs. Frederick (Augusta Tyler)',
  'Name_Graham, Miss. Margaret Edith',
  'Name_Graham, Mr. George Edward',
  'Name_Graham, Mrs. William Thompson (Edith Junkins)',
  'Name_Green, Mr. George Henry',
  'Name_Greenberg, Mr. Samuel',
  'Name_Greenfield, Mr. William Bertram',
  'Name_Gronnestad, Mr. Daniel Danielsen',
  'Name_Guggenheim, Mr. Benjamin',
  'Name_Gustafsson, Mr. Alfred Ossian',
  'Name_Gustafsson, Mr. Anders Vilhelm',
  'Name_Gustafsson, Mr. Johan Birger',
  'Name_Gustafsson, Mr. Karl Gideon',
  'Name_Haas, Miss. Aloisia',
  'Name_Hagland, Mr. Ingvald Olai Olsen',
  'Name_Hagland, Mr. Konrad Mathias Reiersen',
  'Name_Hakkarainen, Mr. Pekka Pietari',
  'Name_Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
  'Name_Hale, Mr. Reginald',
  'Name_Hamalainen, Master. Viljo',
  'Name_Hamalainen, Mrs. William (Anna)',
  'Name_Hampe, Mr. Leon',
  'Name_Hanna, Mr. Mansour',
  'Name_Hansen, Mr. Claus Peter',
  'Name_Hansen, Mr. Henrik Juul',
  'Name_Hansen, Mr. Henry Damsgaard',
  'Name_Harder, Mr. George Achilles',
  'Name_Harknett, Miss. Alice Phoebe',
  'Name_Harmer, Mr. Abraham (David Lishin)',
  'Name_Harper, Miss. Annie Jessie "Nina"',
  'Name_Harper, Mr. Henry Sleeper',
  'Name_Harper, Mrs. Henry Sleeper (Myna Haxtun)',
  'Name_Harper, Rev. John',
  'Name_Harrington, Mr. Charles H',
  'Name_Harris, Mr. George',
  'Name_Harris, Mr. Henry Birkhardt',
  'Name_Harris, Mr. Walter',
  'Name_Harris, Mrs. Henry Birkhardt (Irene Wallach)',
  'Name_Harrison, Mr. William',
  'Name_Hart, Miss. Eva Miriam',
  'Name_Hart, Mr. Benjamin',
  'Name_Hart, Mr. Henry',
  'Name_Hart, Mrs. Benjamin (Esther Ada Bloomfield)',
  'Name_Hassab, Mr. Hammad',
  'Name_Hassan, Mr. Houssein G N',
  'Name_Hawksford, Mr. Walter James',
  'Name_Hays, Miss. Margaret Bechstein',
  'Name_Hays, Mrs. Charles Melville (Clara Jennings Gregg)',
  'Name_Healy, Miss. Hanora "Nora"',
  'Name_Hedman, Mr. Oskar Arvid',
  'Name_Hegarty, Miss. Hanora "Nora"',
  'Name_Heikkinen, Miss. Laina',
  'Name_Heininen, Miss. Wendla Maria',
  'Name_Hendekovic, Mr. Ignjac',
  'Name_Henry, Miss. Delia',
  'Name_Herman, Miss. Alice',
  'Name_Herman, Mrs. Samuel (Jane Laver)',
  'Name_Hewlett, Mrs. (Mary D Kingcome) ',
  'Name_Hickman, Mr. Leonard Mark',
  'Name_Hickman, Mr. Lewis',
  'Name_Hickman, Mr. Stanley George',
  'Name_Hippach, Miss. Jean Gertrude',
  'Name_Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
  'Name_Hirvonen, Miss. Hildur E',
  'Name_Hocking, Mr. Richard George',
  'Name_Hocking, Mrs. Elizabeth (Eliza Needs)',
  'Name_Hodges, Mr. Henry Price',
  'Name_Hogeboom, Mrs. John C (Anna Andrews)',
  'Name_Hold, Mr. Stephen',
  'Name_Holm, Mr. John Fredrik Alexander',
  'Name_Holverson, Mr. Alexander Oskar',
  'Name_Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
  'Name_Homer, Mr. Harry ("Mr E Haven")',
  'Name_Honkanen, Miss. Eliina',
  'Name_Hood, Mr. Ambrose Jr',
  'Name_Horgan, Mr. John',
  'Name_Hosono, Mr. Masabumi',
  'Name_Hoyt, Mr. Frederick Maxfield',
  'Name_Hoyt, Mr. William Fisher',
  'Name_Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
  'Name_Humblen, Mr. Adolf Mathias Nicolai Olsen',
  'Name_Hunt, Mr. George Henry',
  'Name_Ibrahim Shawah, Mr. Yousseff',
  'Name_Icard, Miss. Amelie',
  'Name_Ilett, Miss. Bertha',
  'Name_Ilmakangas, Miss. Pieta Sofia',
  'Name_Isham, Miss. Ann Elizabeth',
  'Name_Ivanoff, Mr. Kanio',
  'Name_Jacobsohn, Mr. Sidney Samuel',
  'Name_Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)',
  'Name_Jalsevac, Mr. Ivan',
  'Name_Jansson, Mr. Carl Olof',
  'Name_Jardin, Mr. Jose Neto',
  'Name_Jarvis, Mr. John Denzil',
  'Name_Jenkin, Mr. Stephen Curnow',
  'Name_Jensen, Mr. Hans Peder',
  'Name_Jensen, Mr. Niels Peder',
  'Name_Jensen, Mr. Svend Lauritz',
  'Name_Jermyn, Miss. Annie',
  'Name_Jerwan, Mrs. Amin S (Marie Marthe Thuillard)',
  'Name_Johannesen-Bratthammer, Mr. Bernt',
  'Name_Johanson, Mr. Jakob Alfred',
  'Name_Johansson, Mr. Erik',
  'Name_Johansson, Mr. Gustaf Joel',
  'Name_Johansson, Mr. Karl Johan',
  'Name_Johnson, Master. Harold Theodor',
  'Name_Johnson, Miss. Eleanor Ileen',
  'Name_Johnson, Mr. Alfred',
  'Name_Johnson, Mr. Malkolm Joackim',
  'Name_Johnson, Mr. William Cahoone Jr',
  'Name_Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
  'Name_Johnston, Miss. Catherine Helen "Carrie"',
  'Name_Johnston, Mr. Andrew G',
  'Name_Jonkoff, Mr. Lalio',
  'Name_Jonsson, Mr. Carl',
  'Name_Jussila, Miss. Katriina',
  'Name_Jussila, Miss. Mari Aina',
  'Name_Jussila, Mr. Eiriik',
  'Name_Kallio, Mr. Nikolai Erland',
  'Name_Kalvik, Mr. Johannes Halvorsen',
  'Name_Kantor, Mr. Sinai',
  'Name_Kantor, Mrs. Sinai (Miriam Sternin)',
  'Name_Karaic, Mr. Milan',
  'Name_Karlsson, Mr. Nils August',
  'Name_Karun, Miss. Manca',
  'Name_Kassem, Mr. Fared',
  'Name_Keane, Miss. Nora A',
  'Name_Keane, Mr. Andrew "Andy"',
  'Name_Keefe, Mr. Arthur',
  'Name_Kelly, Miss. Anna Katherine "Annie Kate"',
  'Name_Kelly, Miss. Mary',
  'Name_Kelly, Mr. James',
  'Name_Kelly, Mrs. Florence "Fannie"',
  'Name_Kent, Mr. Edward Austin',
  'Name_Kenyon, Mrs. Frederick R (Marion)',
  'Name_Kiernan, Mr. Philip',
  'Name_Kilgannon, Mr. Thomas J',
  'Name_Kimball, Mr. Edwin Nelson Jr',
  'Name_Kink, Mr. Vincenz',
  'Name_Kink-Heilmann, Miss. Luise Gretchen',
  'Name_Kirkland, Rev. Charles Leonard',
  'Name_Klaber, Mr. Herman',
  'Name_Klasen, Mr. Klas Albin',
  'Name_Knight, Mr. Robert J',
  'Name_Kraeff, Mr. Theodor',
  'Name_Kvillner, Mr. Johan Henrik Johannesson',
  'Name_Lahoud, Mr. Sarkis',
  'Name_Lahtinen, Mrs. William (Anna Sylfven)',
  'Name_Laitinen, Miss. Kristina Sofia',
  'Name_Laleff, Mr. Kristo',
  'Name_Lam, Mr. Ali',
  'Name_Lam, Mr. Len',
  'Name_Landergren, Miss. Aurora Adelia',
  'Name_Lang, Mr. Fang',
  'Name_Laroche, Miss. Simonne Marie Anne Andree',
  'Name_Laroche, Mr. Joseph Philippe Lemercier',
  'Name_Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)',
  'Name_Larsson, Mr. August Viktor',
  'Name_Larsson, Mr. Bengt Edvin',
  'Name_LeRoy, Miss. Bertha',
  'Name_Leader, Dr. Alice (Farnham)',
  'Name_Leeni, Mr. Fahim ("Philip Zenni")',
  'Name_Lefebre, Master. Henry Forbes',
  'Name_Lefebre, Miss. Ida',
  'Name_Lefebre, Miss. Jeannie',
  'Name_Lefebre, Miss. Mathilde',
  'Name_Lehmann, Miss. Bertha',
  'Name_Leinonen, Mr. Antti Gustaf',
  'Name_Leitch, Miss. Jessie Wills',
  'Name_Lemberopolous, Mr. Peter L',
  'Name_Lemore, Mrs. (Amelia Milley)',
  'Name_Lennon, Mr. Denis',
  'Name_Leonard, Mr. Lionel',
  'Name_Lester, Mr. James',
  'Name_Lesurer, Mr. Gustave J',
  'Name_Levy, Mr. Rene Jacques',
  'Name_Lewy, Mr. Ervin G',
  'Name_Leyson, Mr. Robert William Norman',
  'Name_Lievens, Mr. Rene Aime',
  'Name_Lindahl, Miss. Agda Thorilda Viktoria',
  'Name_Lindblom, Miss. Augusta Charlotta',
  'Name_Lindell, Mr. Edvard Bengtsson',
  'Name_Lindqvist, Mr. Eino William',
  'Name_Lines, Miss. Mary Conover',
  'Name_Ling, Mr. Lee',
  'Name_Lobb, Mr. William Arthur',
  'Name_Lobb, Mrs. William Arthur (Cordelia K Stanlick)',
  'Name_Long, Mr. Milton Clyde',
  'Name_Longley, Miss. Gretchen Fiske',
  'Name_Louch, Mrs. Charles Alexander (Alice Adelaide Slow)',
  'Name_Lovell, Mr. John Hall ("Henry")',
  'Name_Lulic, Mr. Nikola',
  'Name_Lundahl, Mr. Johan Svensson',
  'Name_Lurette, Miss. Elise',
  'Name_Mack, Mrs. (Mary)',
  'Name_Madigan, Miss. Margaret "Maggie"',
  'Name_Madill, Miss. Georgette Alexandra',
  'Name_Madsen, Mr. Fridtjof Arne',
  'Name_Maenpaa, Mr. Matti Alexanteri',
  'Name_Maioni, Miss. Roberta',
  'Name_Maisner, Mr. Simon',
  'Name_Mallet, Master. Andre',
  'Name_Mallet, Mr. Albert',
  'Name_Mamee, Mr. Hanna',
  'Name_Mangan, Miss. Mary',
  'Name_Mannion, Miss. Margareth',
  'Name_Marechal, Mr. Pierre',
  'Name_Markoff, Mr. Marin',
  'Name_Markun, Mr. Johann',
  'Name_Marvin, Mr. Daniel Warner',
  'Name_Masselmani, Mrs. Fatima',
  'Name_Matthews, Mr. William John',
  'Name_Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")',
  'Name_McCarthy, Mr. Timothy J',
  'Name_McCormack, Mr. Thomas Joseph',
  'Name_McCoy, Miss. Agnes',
  'Name_McCoy, Mr. Bernard',
  'Name_McDermott, Miss. Brigdet Delia',
  'Name_McEvoy, Mr. Michael',
  'Name_McGough, Mr. James Robert',
  'Name_McGovern, Miss. Mary',

Поля Name и Ticket особой пользы не несут и при one-hot обработку делают данные сильно разреженными, продемонстрирую таблицу без этих столбцов)

In [31]:
df = df.drop(['Name', 'Ticket'], axis=1)

In [32]:
preprocessor = DataPreprocessor(df)

In [33]:
df_clean = preprocessor.fit_transform()

In [34]:
df_clean

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0.000000,0.0,1.0,0.271174,0.125,0.000000,0.014151,0.0,1.0,0.0,0.0,1.0
1,0.001124,1.0,0.0,0.472229,0.125,0.000000,0.139136,1.0,0.0,1.0,0.0,0.0
2,0.002247,1.0,1.0,0.321438,0.000,0.000000,0.015469,1.0,0.0,0.0,0.0,1.0
3,0.003371,1.0,0.0,0.434531,0.125,0.000000,0.103644,1.0,0.0,0.0,0.0,1.0
4,0.004494,0.0,1.0,0.434531,0.000,0.000000,0.015713,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0.995506,0.0,0.5,0.334004,0.000,0.000000,0.025374,0.0,1.0,0.0,0.0,1.0
887,0.996629,1.0,0.0,0.233476,0.000,0.000000,0.058556,1.0,0.0,0.0,0.0,1.0
888,0.997753,0.0,1.0,0.346569,0.125,0.333333,0.045771,1.0,0.0,0.0,0.0,1.0
889,0.998876,1.0,0.0,0.321438,0.000,0.000000,0.058556,0.0,1.0,1.0,0.0,0.0
890,1.000000,0.0,1.0,0.396833,0.000,0.000000,0.015127,0.0,1.0,0.0,1.0,0.0